### ISSUE TITLE
centrifuge build version

### ISSUE THREAD

**Issue by JesseKerkvliet** [lisavader/plasmidEC#12]
Hi, Julian and I spent the better part of today trying to figure out why his plascope did something different compared to mine. The outcome: I had an older build version of centrifuge.

Proposed solution: hardcode the build version of centrifuge in the command installing plascope/centrifuge in the plasmidEC_plascope environment, or (in the case this is handled by plascope) update it after installing plascope.

Code that solved my issue:
`conda install centrifuge=1.0.3=py36pl5.22.0_3 -c bioconda`

**Comment by lisavader** [comment]
Hi Jesse,
I thought that the plascope conda environment would include a specific version of centrifuge, but this is apparently not the case.
I will implement your solution.

**Comment by lisavader** [comment]
Closed by 8913a0d9c8cd9b013d42452ca141e9cc3067d350
