### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by jpaganini** [lisavader/plasmidEC#4]
Wish list
- [x] getting the gplas-formatted output should be optional, with a flag.
- [x] multi-threading the individual tools, if possible
- [x] input as file instead of directory
- [x] fasta file with all the plasmid sequences
- [x] provide tools selection as default. Optional flag to choose different tools.
- [x] update readme + add help flag
- [x] add version

**Comment by lisavader** [comment]
Closed by #6
