### ISSUE TITLE
Problem with Argument parsing

### ISSUE THREAD

**Issue by varunshamanna** [lisavader/plasmidEC#9]
There is some problem with the way the arguments are handled.
If I don't give -g before -t the $threads will be null and $SCRIPT_DIR will not be parsed into the subscripts
```
while getopts :i:c:o:fgtvh flag; do
```

Changed to 
```
while getopts ":i:c:o:fgt:vh:" flag; do
```
Now working fine but still needs your review.

**Comment by lisavader** [comment]
Hi Varun,
Thanks for spotting the issue, I've now added the missing colon for --threads (f06f04bc7dba6617aff5d365828bdece148d2473)
